baseURL = 'https://mgwinsor.dev/'
theme = "risotto"
title = 'mgwinsor dev'
author = 'Michael Winsor'
languageCode = 'en-us'
DefaultContentLanguage = "en"
paginate = 3
enableInlineShortcodes = true
enableRobotsTXT = true

ignoreErrors = ["error-remote-getjson"]

sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "windows-95"

[params.about]
title = "mgwinsor"
description = "Welcome to my personal website."
# logo = "ðŸš"
# logo_image = "images/rice.svg"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/mgwinsor"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:mgwinsor@gmail.com"

[[params.socialLinks]]
icon = "ai ai-orcid"
title = "ORCID"
url = "https://orcid.org/0000-0001-2345-6789"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects/"
    weight = 30

  [[menu.main]]
    identifier = "resume"
    name = "resume"
    url = "/resume.pdf"
    weight = 40
    [menu.main.params]
      newPage = true

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 50

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

# [params]
#   description = "Data Engineer"
#   avatarURL = "/images/avatar.png"
#   AvatarAltTest = "avatar"
#   avatarSize = "size-l"
#   socialIcons = [
#     {name = "github", url = "https://github.com/mgwinsor"},
#     {name = "linkedin", url = "https://linkedin.com/in/mgwinsor"},
#     {name = "email", url = "mailto:mgwinsor@gmail.com"}
#   ]
#   ShowBackToTopButton = true
#   footer = "mgwinsor.dev"
#   metaKeywords = ["blog", "portfolio", "software", "data", "engineering"]
#
# [params.meta]
#   favicon = true

# [markup]
#   [markup.tableOfContents]
#     startLevel = 1
#     endLevel = 4
#     ordered = false
